# Identitas Diri
Nama : Aditya Herdiansyah Putra  
NIM  : A11.2021.13948

# Menambahkan library
 "numpy" berguna memudahkan kita melakukan perhitungan saintifik seperti matriks, aljabar, statistik, dan sebagainya.    
 "pandas" berguna untuk memproses data, mulai pembersihan data, manipulasi data, hingga melakukan analisis data.        
 "sklearn import tree" berguna dalam membangun model decision tree untuk masalah klasifikasi dan regresi, menghitung impurity, menghasilkan visualisasi decision tree, dan melakukan prediksi pada data baru.

In [31]:
import numpy as np
import pandas as pd
from sklearn import tree

# Membaca dataset dari file ke pandas dataframe

In [48]:
FishDataset = pd.read_csv('Fish.csv')

In [49]:
FishDataset.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

# Mengubah keals (kolom "Species") dari String ke Unique-Integer

In [50]:
FishDataset["Species"] = pd.factorize(FishDataset.Species)[0]

In [51]:
FishDataset.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0        0   242.0     23.2     25.4     30.0  11.5200  4.0200
1        0   290.0     24.0     26.3     31.2  12.4800  4.3056
2        0   340.0     23.9     26.5     31.1  12.3778  4.6961
3        0   363.0     26.3     29.0     33.5  12.7300  4.4555
4        0   430.0     26.5     29.0     34.0  12.4440  5.1340

In [52]:
print(FishDataset)

     Species  Weight  Length1  Length2  Length3   Height   Width
0          0   242.0     23.2     25.4     30.0  11.5200  4.0200
1          0   290.0     24.0     26.3     31.2  12.4800  4.3056
2          0   340.0     23.9     26.5     31.1  12.3778  4.6961
3          0   363.0     26.3     29.0     33.5  12.7300  4.4555
4          0   430.0     26.5     29.0     34.0  12.4440  5.1340
..       ...     ...      ...      ...      ...      ...     ...
145        0     6.7      9.3      9.8     10.8   1.7388  1.0476
146        0     7.5     10.0     10.5     11.6   1.9720  1.1600
147        0     7.0     10.1     10.6     11.6   1.7284  1.1484
148        0     9.7     10.4     11.0     12.0   2.1960  1.3800
149        0     9.8     10.7     11.2     12.4   2.0832  1.2772

[150 rows x 7 columns]


# Mengubah dataFrame ke Array Numpy

In [53]:
FishDataset = FishDataset.to_numpy()

In [54]:
print(FishDataset)

[[  0.     242.      23.2    ...  30.      11.52     4.02  ]
 [  0.     290.      24.     ...  31.2     12.48     4.3056]
 [  0.     340.      23.9    ...  31.1     12.3778   4.6961]
 ...
 [  0.       7.      10.1    ...  11.6      1.7284   1.1484]
 [  0.       9.7     10.4    ...  12.       2.196    1.38  ]
 [  0.       9.8     10.7    ...  12.4      2.0832   1.2772]]


# Membagi dataset 
membagi dataset untuk data training yaitu sebanyak 120 baris untuk data training dan untuk data testing sebanyak 30 baris.

In [55]:
dataTraining = np.concatenate((FishDataset[0:60, :], FishDataset[75:135, :]), 
                              axis=0)
dataTesting = np.concatenate((FishDataset[60:75, :], FishDataset[135:150, :]),
                              axis=0)

In [56]:
print(dataTraining)
len(dataTraining)

[[0.00000e+00 2.42000e+02 2.32000e+01 2.54000e+01 3.00000e+01 1.15200e+01
  4.02000e+00]
 [0.00000e+00 2.90000e+02 2.40000e+01 2.63000e+01 3.12000e+01 1.24800e+01
  4.30560e+00]
 [0.00000e+00 3.40000e+02 2.39000e+01 2.65000e+01 3.11000e+01 1.23778e+01
  4.69610e+00]
 [0.00000e+00 3.63000e+02 2.63000e+01 2.90000e+01 3.35000e+01 1.27300e+01
  4.45550e+00]
 [0.00000e+00 4.30000e+02 2.65000e+01 2.90000e+01 3.40000e+01 1.24440e+01
  5.13400e+00]
 [0.00000e+00 4.50000e+02 2.68000e+01 2.97000e+01 3.47000e+01 1.36024e+01
  4.92740e+00]
 [0.00000e+00 5.00000e+02 2.68000e+01 2.97000e+01 3.45000e+01 1.41795e+01
  5.27850e+00]
 [0.00000e+00 3.90000e+02 2.76000e+01 3.00000e+01 3.50000e+01 1.26700e+01
  4.69000e+00]
 [0.00000e+00 4.50000e+02 2.76000e+01 3.00000e+01 3.51000e+01 1.40049e+01
  4.84380e+00]
 [0.00000e+00 5.00000e+02 2.85000e+01 3.07000e+01 3.62000e+01 1.42266e+01
  4.95940e+00]
 [0.00000e+00 4.75000e+02 2.84000e+01 3.10000e+01 3.62000e+01 1.42628e+01
  5.10420e+00]
 [0.00000e+00 5.00000

120

In [57]:
print(dataTesting)
len(dataTesting)

[[0.00000e+00 1.00000e+03 3.73000e+01 4.00000e+01 4.35000e+01 1.23540e+01
  6.52500e+00]
 [2.00000e+00 5.50000e+01 1.35000e+01 1.47000e+01 1.65000e+01 6.84750e+00
  2.32650e+00]
 [2.00000e+00 6.00000e+01 1.43000e+01 1.55000e+01 1.74000e+01 6.57720e+00
  2.31420e+00]
 [2.00000e+00 9.00000e+01 1.63000e+01 1.77000e+01 1.98000e+01 7.40520e+00
  2.67300e+00]
 [2.00000e+00 1.20000e+02 1.75000e+01 1.90000e+01 2.13000e+01 8.39220e+00
  2.91810e+00]
 [2.00000e+00 1.50000e+02 1.84000e+01 2.00000e+01 2.24000e+01 8.89280e+00
  3.29280e+00]
 [2.00000e+00 1.40000e+02 1.90000e+01 2.07000e+01 2.32000e+01 8.53760e+00
  3.29440e+00]
 [2.00000e+00 1.70000e+02 1.90000e+01 2.07000e+01 2.32000e+01 9.39600e+00
  3.41040e+00]
 [2.00000e+00 1.45000e+02 1.98000e+01 2.15000e+01 2.41000e+01 9.73640e+00
  3.15710e+00]
 [2.00000e+00 2.00000e+02 2.12000e+01 2.30000e+01 2.58000e+01 1.03458e+01
  3.66360e+00]
 [2.00000e+00 2.73000e+02 2.30000e+01 2.50000e+01 2.80000e+01 1.10880e+01
  4.14400e+00]
 [2.00000e+00 3.00000

30

# Memecah Dataset ke Input dan Label

In [60]:
inputTraining = dataTraining[:, 1:6]
inputTesting = dataTesting[:, 1:6]
labelTraining = dataTraining[:, 0]
labelTesting = dataTesting[:, 0]

# Mendefinisikan Decision Tree Classifier

In [61]:
model = tree.DecisionTreeClassifier()

# Mentraining Model

In [62]:
model = model.fit(inputTraining, labelTraining)

# Memprediksi Input Data Testing

In [63]:
hasilPrediksi = model.predict(inputTesting)
print ("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi   : ", hasilPrediksi)

Label Sebenarnya :  [0. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 0. 0. 0. 0. 0.]
Hasil Prediksi   :  [2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 0. 0. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2.
 2. 1. 1. 1. 1. 1.]


# Menghitung Akurasi

In [64]:
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar   : ", prediksiBenar, "data")
print("Prediksi Salah   : ", prediksiSalah, "data")
print("Akurasi          : ", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar   :  4 data
Prediksi Salah   :  26 data
Akurasi          :  13.333333333333334 %
